/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemoryMemoryIdRouteImport } from './routes/memory.$memoryId'
import { Route as GroupPlanPlanIdRouteImport } from './routes/group-plan.$planId'

const GroupPlanPlanIdRoute = GroupPlanPlanIdRouteImport.update({
  id: '/group-plan/$planId',
  path: '/group-plan/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryMemoryIdRoute = MemoryMemoryIdRouteImport.update({
  id: '/memory/$memoryId',
  path: '/memory/$memoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/memory/$memoryId': typeof MemoryMemoryIdRoute
  '/group-plan/$planId': typeof GroupPlanPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/memory/$memoryId': typeof MemoryMemoryIdRoute
  '/group-plan/$planId': typeof GroupPlanPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/memory/$memoryId': typeof MemoryMemoryIdRoute
  '/group-plan/$planId': typeof GroupPlanPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/calendar' | '/memory/$memoryId' | '/group-plan/$planId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/calendar' | '/memory/$memoryId' | '/group-plan/$planId'
  id: '__root__' | '/' | '/auth' | '/calendar' | '/memory/$memoryId' | '/group-plan/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  MemoryMemoryIdRoute: typeof MemoryMemoryIdRoute
  GroupPlanPlanIdRoute: typeof GroupPlanPlanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/group-plan/$planId': {
      id: '/group-plan/$planId'
      path: '/group-plan/$planId'
      fullPath: '/group-plan/$planId'
      preLoaderRoute: typeof GroupPlanPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/$memoryId': {
      id: '/memory/$memoryId'
      path: '/memory/$memoryId'
      fullPath: '/memory/$memoryId'
      preLoaderRoute: typeof MemoryMemoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  MemoryMemoryIdRoute: MemoryMemoryIdRoute,
  GroupPlanPlanIdRoute: GroupPlanPlanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
